import { Droplets, Info, Leaf } from "lucide-react";
import React from "react";
import Modal from "../Modal/Modal";

export interface EnvironmentalImpactModalProps {
  isOpen?: boolean;
  onClose?: () => void;
  environmentalImpact: {
    totalCo2SavingsKG: number;
    totalWaterSavingsLT: number;
    materialBreakdown: Array<{
      materialType: string;
      percentage: number;
      weightKG: number;
      co2SavingsKG: number;
      waterSavingsLT: number;
    }>;
  };
  co2SavingsTitle?: string;
  waterSavingsTitle?: string;
  weightLabel?: string;
  co2SavingsLabel?: string;
  waterSavingsLabel?: string;
  materialBreakdownLabel?: string;
  co2EquivalenceLabel?: string;
  waterEquivalenceLabel?: string;
  infoText?: string;
  carDistanceLabel?: string;
  showerCountLabel?: string;
}

function formatNumber(num: number): string {
  return num.toLocaleString("es-CL", { minimumFractionDigits: 1, maximumFractionDigits: 1 });
}

function ProgressBar({ percentage }: { percentage: number }) {
  return (
    <div className="h-1.5 overflow-hidden rounded-full bg-primary/10">
      {/* width is data-driven, so it stays inline */}
      <div className="h-full rounded-full bg-primary" style={{ width: `${percentage}%` }} />
    </div>
  );
}

export default function EnvironmentalImpactModal({
  isOpen,
  onClose,
  environmentalImpact,
  co2SavingsTitle = "CO₂ Savings",
  waterSavingsTitle = "Water Savings",
  weightLabel = "Weight",
  co2SavingsLabel = "CO₂ Saved",
  waterSavingsLabel = "Water Saved",
  materialBreakdownLabel = "Material Breakdown",
  co2EquivalenceLabel = "Equivalent to",
  waterEquivalenceLabel = "Equivalent to",
  infoText = "These values are estimates based on the savings generated by reusing products instead of manufacturing new ones.",
  carDistanceLabel = " by car",
  showerCountLabel = " showers",
}: EnvironmentalImpactModalProps) {
  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Detailed Environmental Impact" size="md">
      <div className="flex flex-col gap-5">
        {/* Summary cards */}
        <div className="flex flex-row gap-3">
          {/* CO₂ card */}
          <div className="flex flex-1 flex-col gap-1 rounded-md bg-success/10 p-3.5">
            <div className="mb-1 flex flex-row items-center gap-1.5">
              <Leaf size={18} color="currentColor" strokeWidth={2} className="text-success" />
              <span className="min-w-0 flex-1 font-sans text-sm font-medium text-foreground-secondary">
                {co2SavingsTitle}
              </span>
            </div>
            <span className="font-sans text-xl font-bold tracking-[-0.5px] text-success">
              {formatNumber(environmentalImpact.totalCo2SavingsKG)} kg
            </span>
            <span className="font-sans text-xs font-normal leading-3.75 text-foreground-secondary">
              {co2EquivalenceLabel} {formatNumber(environmentalImpact.totalCo2SavingsKG * 4.5)} km
              {carDistanceLabel}
            </span>
          </div>

          {/* Water card */}
          <div className="flex flex-1 flex-col gap-1 rounded-md bg-info/10 p-3.5">
            <div className="mb-1 flex flex-row items-center gap-1.5">
              <Droplets size={18} color="currentColor" strokeWidth={2} className="text-info" />
              <span className="min-w-0 flex-1 font-sans text-sm font-medium text-foreground-secondary">
                {waterSavingsTitle}
              </span>
            </div>
            <span className="font-sans text-xl font-bold tracking-[-0.5px] text-info">
              {formatNumber(environmentalImpact.totalWaterSavingsLT)} L
            </span>
            <span className="font-sans text-xs font-normal leading-3.75 text-foreground-secondary">
              {waterEquivalenceLabel} {formatNumber(environmentalImpact.totalWaterSavingsLT / 8)}
              {showerCountLabel}
            </span>
          </div>
        </div>

        {/* Material breakdown */}
        {environmentalImpact.materialBreakdown.length > 0 && (
          <div className="flex flex-col gap-3">
            <div className="flex flex-row items-center gap-2">
              <Info size={18} color="currentColor" strokeWidth={2} className="text-foreground" />
              <span className="font-sans text-base font-bold text-foreground">
                {materialBreakdownLabel}
              </span>
            </div>

            <div className="flex flex-col gap-2.5">
              {environmentalImpact.materialBreakdown.map((material, index) => (
                <div
                  key={index}
                  className="flex flex-col gap-2.5 rounded-md border border-border-light p-3.5"
                >
                  <div className="flex flex-row items-center justify-between">
                    <span className="flex-1 font-sans text-sm font-semibold text-foreground">
                      {material.materialType}
                    </span>
                    <span className="font-sans text-base font-bold text-primary">
                      {material.percentage.toFixed(1)}%
                    </span>
                  </div>

                  <div className="flex flex-row gap-2">
                    <div className="flex flex-1 flex-col gap-0.5">
                      <span className="font-sans text-xs font-normal text-foreground-secondary">
                        {weightLabel}
                      </span>
                      <span className="font-sans text-sm font-semibold text-foreground">
                        {formatNumber(material.weightKG)} kg
                      </span>
                    </div>
                    <div className="flex flex-1 flex-col gap-0.5">
                      <span className="font-sans text-xs font-normal text-foreground-secondary">
                        {co2SavingsLabel}
                      </span>
                      <span className="font-sans text-sm font-semibold text-success">
                        {formatNumber(material.co2SavingsKG)} kg
                      </span>
                    </div>
                    <div className="flex flex-1 flex-col gap-0.5">
                      <span className="font-sans text-xs font-normal text-foreground-secondary">
                        {waterSavingsLabel}
                      </span>
                      <span className="font-sans text-sm font-semibold text-info">
                        {formatNumber(material.waterSavingsLT)} L
                      </span>
                    </div>
                  </div>

                  <ProgressBar percentage={material.percentage} />
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Info footer */}
        <div className="flex flex-row items-start gap-2 rounded-md bg-primary/5 p-3.5">
          <div className="mt-px shrink-0 text-primary">
            <Info size={14} color="currentColor" strokeWidth={2} />
          </div>
          <span className="flex-1 font-sans text-xs font-normal leading-4.5 text-foreground-secondary">
            {infoText}
          </span>
        </div>
      </div>
    </Modal>
  );
}
