import { borderRadius, colors, fontFamily, fontSize } from "@/design/tokens";
import { Droplets, Info, Leaf } from "lucide-react";
import React from "react";
import Modal from "../Modal/Modal";

export interface EnvironmentalImpactModalProps {
  isOpen?: boolean;
  onClose?: () => void;
  environmentalImpact: {
    totalCo2SavingsKG: number;
    totalWaterSavingsLT: number;
    materialBreakdown: Array<{
      materialType: string;
      percentage: number;
      weightKG: number;
      co2SavingsKG: number;
      waterSavingsLT: number;
    }>;
  };
  co2SavingsTitle?: string;
  waterSavingsTitle?: string;
  weightLabel?: string;
  co2SavingsLabel?: string;
  waterSavingsLabel?: string;
  materialBreakdownLabel?: string;
  co2EquivalenceLabel?: string;
  waterEquivalenceLabel?: string;
  infoText?: string;
  carDistanceLabel?: string;
  showerCountLabel?: string;
}

function formatNumber(num: number): string {
  return num.toLocaleString("es-CL", { minimumFractionDigits: 1, maximumFractionDigits: 1 });
}

function ProgressBar({ percentage }: { percentage: number }) {
  return (
    <div
      style={{
        height: 6,
        backgroundColor: `${colors.primary}1A`,
        borderRadius: borderRadius.full,
        overflow: "hidden",
      }}
    >
      <div
        style={{
          height: "100%",
          backgroundColor: colors.primary,
          borderRadius: borderRadius.full,
          width: `${percentage}%`,
        }}
      />
    </div>
  );
}

export default function EnvironmentalImpactModal({
  isOpen,
  onClose,
  environmentalImpact,
  co2SavingsTitle = "CO₂ Savings",
  waterSavingsTitle = "Water Savings",
  weightLabel = "Weight",
  co2SavingsLabel = "CO₂ Saved",
  waterSavingsLabel = "Water Saved",
  materialBreakdownLabel = "Material Breakdown",
  co2EquivalenceLabel = "Equivalent to",
  waterEquivalenceLabel = "Equivalent to",
  infoText = "These values are estimates based on the savings generated by reusing products instead of manufacturing new ones.",
  carDistanceLabel = " by car",
  showerCountLabel = " showers",
}: EnvironmentalImpactModalProps) {
  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Detailed Environmental Impact" size="md">
      <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>

        {/* Summary cards */}
        <div style={{ display: "flex", flexDirection: "row", gap: 12 }}>
          {/* CO₂ card */}
          <div
            style={{
              flex: 1,
              borderRadius: borderRadius.md,
              padding: 14,
              display: "flex",
              flexDirection: "column",
              gap: 4,
              backgroundColor: `${colors.success}1A`,
            }}
          >
            <div style={{ display: "flex", flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 4 }}>
              <Leaf size={18} color={colors.success} strokeWidth={2} />
              <span style={{ fontSize: fontSize.sm, fontFamily: fontFamily.sans, fontWeight: 500, color: colors.foregroundSecondary, flex: 1, minWidth: 0 }}>
                {co2SavingsTitle}
              </span>
            </div>
            <span style={{ fontSize: fontSize.xl, fontFamily: fontFamily.sans, fontWeight: 700, letterSpacing: -0.5, color: colors.success }}>
              {formatNumber(environmentalImpact.totalCo2SavingsKG)} kg
            </span>
            <span style={{ fontSize: fontSize.xs, fontFamily: fontFamily.sans, fontWeight: 400, color: colors.foregroundSecondary, lineHeight: "15px" }}>
              {co2EquivalenceLabel} {formatNumber(environmentalImpact.totalCo2SavingsKG * 4.5)} km{carDistanceLabel}
            </span>
          </div>

          {/* Water card */}
          <div
            style={{
              flex: 1,
              borderRadius: borderRadius.md,
              padding: 14,
              display: "flex",
              flexDirection: "column",
              gap: 4,
              backgroundColor: `${colors.info}1A`,
            }}
          >
            <div style={{ display: "flex", flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 4 }}>
              <Droplets size={18} color={colors.info} strokeWidth={2} />
              <span style={{ fontSize: fontSize.sm, fontFamily: fontFamily.sans, fontWeight: 500, color: colors.foregroundSecondary, flex: 1, minWidth: 0 }}>
                {waterSavingsTitle}
              </span>
            </div>
            <span style={{ fontSize: fontSize.xl, fontFamily: fontFamily.sans, fontWeight: 700, letterSpacing: -0.5, color: colors.info }}>
              {formatNumber(environmentalImpact.totalWaterSavingsLT)} L
            </span>
            <span style={{ fontSize: fontSize.xs, fontFamily: fontFamily.sans, fontWeight: 400, color: colors.foregroundSecondary, lineHeight: "15px" }}>
              {waterEquivalenceLabel} {formatNumber(environmentalImpact.totalWaterSavingsLT / 8)}{showerCountLabel}
            </span>
          </div>
        </div>

        {/* Material breakdown */}
        {environmentalImpact.materialBreakdown.length > 0 && (
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            <div style={{ display: "flex", flexDirection: "row", alignItems: "center", gap: 8 }}>
              <Info size={18} color={colors.foreground} strokeWidth={2} />
              <span style={{ fontSize: fontSize.base, fontFamily: fontFamily.sans, fontWeight: 700, color: colors.foreground }}>
                {materialBreakdownLabel}
              </span>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {environmentalImpact.materialBreakdown.map((material, index) => (
                <div
                  key={index}
                  style={{
                    border: `1px solid ${colors.borderLight}`,
                    borderRadius: borderRadius.md,
                    padding: 14,
                    display: "flex",
                    flexDirection: "column",
                    gap: 10,
                  }}
                >
                  <div style={{ display: "flex", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}>
                    <span style={{ fontSize: fontSize.sm, fontFamily: fontFamily.sans, fontWeight: 600, color: colors.foreground, flex: 1 }}>
                      {material.materialType}
                    </span>
                    <span style={{ fontSize: fontSize.base, fontFamily: fontFamily.sans, fontWeight: 700, color: colors.primary }}>
                      {material.percentage.toFixed(1)}%
                    </span>
                  </div>

                  <div style={{ display: "flex", flexDirection: "row", gap: 8 }}>
                    <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 2 }}>
                      <span style={{ fontSize: fontSize.xs, fontFamily: fontFamily.sans, fontWeight: 400, color: colors.foregroundSecondary }}>
                        {weightLabel}
                      </span>
                      <span style={{ fontSize: fontSize.sm, fontFamily: fontFamily.sans, fontWeight: 600, color: colors.foreground }}>
                        {formatNumber(material.weightKG)} kg
                      </span>
                    </div>
                    <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 2 }}>
                      <span style={{ fontSize: fontSize.xs, fontFamily: fontFamily.sans, fontWeight: 400, color: colors.foregroundSecondary }}>
                        {co2SavingsLabel}
                      </span>
                      <span style={{ fontSize: fontSize.sm, fontFamily: fontFamily.sans, fontWeight: 600, color: colors.success }}>
                        {formatNumber(material.co2SavingsKG)} kg
                      </span>
                    </div>
                    <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 2 }}>
                      <span style={{ fontSize: fontSize.xs, fontFamily: fontFamily.sans, fontWeight: 400, color: colors.foregroundSecondary }}>
                        {waterSavingsLabel}
                      </span>
                      <span style={{ fontSize: fontSize.sm, fontFamily: fontFamily.sans, fontWeight: 600, color: colors.info }}>
                        {formatNumber(material.waterSavingsLT)} L
                      </span>
                    </div>
                  </div>

                  <ProgressBar percentage={material.percentage} />
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Info footer */}
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "flex-start",
            gap: 8,
            backgroundColor: `${colors.primary}0D`,
            borderRadius: borderRadius.md,
            padding: 14,
          }}
        >
          <div style={{ marginTop: 1, flexShrink: 0 }}>
            <Info size={14} color={colors.primary} strokeWidth={2} />
          </div>
          <span style={{ flex: 1, fontSize: fontSize.xs, fontFamily: fontFamily.sans, fontWeight: 400, color: colors.foregroundSecondary, lineHeight: "18px" }}>
            {infoText}
          </span>
        </div>

      </div>
    </Modal>
  );
}
